services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oauth_app
    volumes:
      - ./data:/app/data
      - ./keys:/app/keys
    expose:
      - "8080" # Internal only, exposed to Nginx
    depends_on:
      - redis
    environment:
      - SERVER_PORT=8080
      - REDIS_URL=redis:6379
      - DB_PATH=/app/data/app.db
      - JWK_PATH=/app/keys
      - ISSUER_HOST=${ISSUER_HOST}
      - SECRET_KEY=${SECRET_KEY}

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  redis_data:
